"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Syarats",
      [
        {
          name: "Fotokopi Kartu Keluarga (KK)",
          path: "foto_copy_kartu_keluarga",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Berita Acara Penetapan Fakir Uzur dari Desa",
          path: "berita_acara_penetapan_fakir_uzur_dari_desa",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Kurang Mampu",
          path: "surat_keterangan_kurang_mampu",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Kartu Tanda Penduduk ( KTP)",
          path: "foto_copy_kartu_tanda_penduduk",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Buku Rekening",
          path: "foto_copy_buku_rekening",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dokumentasi Keadaan Saat Ini",
          path: "dokumentasi_keadaan_saat_ini",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Buku Rekening atas Nama Mustahik",
          path: "foto_copy_buku_rekening_atas_nama_mustahik",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Permohonan Bantuan di Tujukan Kepada Ketua Baitul Mal",
          path: "surat_permohonan_bantuan_tujuan_kepada_ketua_baitul_mal",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Sertifikat Tanah",
          path: "foto_copy_sertifikat_tanah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Pas Photo Ukuran 3 x 4",
          path: "pas_photo_ukuran_3_4",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Disabilitas Jika Dalam Anggota Keluarga Ada Yang Cacat/ Berkebutuhan Khusus.",
          path: "surat_keterangan_disabilitas_dalam_keluarga",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Rincian Anggaran Biaya ( RAB)",
          path: "rincian_anggaran_biaya_rab",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Sertifikat Muallaf dari MPU.",
          path: "sertifikat_muallaf_mpu",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Buku Rekening Bank Aceh Syariah",
          path: "foto_copy_buku_rekening_bank_aceh_syariah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Korban Musibah dari Reje Kampung;",
          path: "surat_keterangan_korban_musibah_dari_reje_kampung",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dokumentasi",
          path: "dokumentasi",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi KTP atau Fotokopi Identitas Diri Lainnya.",
          path: "foto_copy_ktp_atau_identitas_lainya",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Memorandum of Understanding (MoU)/ Surat Pernyataan Penggunaan Biaya",
          path: "mou_atau_surat_pernyataan_penggunaan_biaya",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Melampirkan Proposal Bantuan  Sarana dan Prasarana Masjid / Menasah / Mushola dan Rincian Anggaran Biaya",
          path: "lampiran_proposal_bantuan_dan_rincian_anggaran",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Kwitansi",
          path: "kwitansi",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "SK Panitia Pengurus Masjid/ Menasah.",
          path: "sk_panitian_pengurus_masjid_menasah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi KTP Ketua Pengurus Masjid.",
          path: "foto_copy_ktp_ketua_pengurus_masjid",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Memiliki Rekening Bank Aceh Syariah Atas Nama Masjid / Menasah.",
          path: "rekening_bank_aceh_syariah_atas_nama_masjid_menasah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi KTP / Identitas Resmi Lainnya",
          path: "foto_copy_ktp_identitas_resmi_lainnya",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dokumentasi Tempat Usaha",
          path: "dokumentasi_tempat_usaha",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Proposal Bantuan Modal Usaha dan Rincian Anggaran Biaya ( RAB)",
          path: "proposal_bantuan_modal_usaha_dan_rab",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Pas Photo Warna Ukuran 3 x 4",
          path: "pas_photo_warna_3_4",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan dari Puskesmas / Rumah Sakit / Bidan Desa Setempat yang Menyatakan Ibu Hamil, Anak Stunting atau Anak Berpotensi Stunting.",
          path: "surat_keterangan_stunting_atau_perpotensi_stunting",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Tidak Mampu yang Ditandatangi oleh Reje Kampung dan Imam Kampung",
          path: "surat_keterangan_tidak_mampu_oleh_reje_atau_imam",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Rujukan dari Rumah Sakit / Puskesmas Setempat Terbaru (untuk bantuan berobat)",
          path: "surat_rujukan_dari_rumah_sakit_pukesmas",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Buku Rekening Bank Aceh Syariah atas Nama Organisasi / Lembaga yang aktif",
          path: "foto_copy_buku_rekening_bank_aceh_organisasi_atau_lembaga",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Aktif Mengajar dari Tempat Mengajar.",
          path: "surat_keterangan_mengajar_dari_tempat_mengajar",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Izin Berdirinya Yayasan / Lembaga dari Pemerintah Daerah;",
          path: "surat_izin_berdiri_yayasan_lembaga_dari_pemerintah_daerah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Izin Oprasional",
          path: "surat_izin_operasional",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi  KTP Pengurus",
          path: "foto_copy_ktp_pengurus",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi KK Pengurus;",
          path: "foto_copy_kk_pengurus",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Perjanjian Kerjasama (SPK) yang Sudah Ditanda Tangan",
          path: "surat_perjanjian_kerjasama_yang_sudah_ditanda_tangan",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "SK Kepanitiaan",
          path: "sk_kepanitiaan",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Aktif Santri",
          path: "surat_keterangan_aktif_santri",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Kartu Tanda Santri / KTS",
          path: "kartu_tanda_santri",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Penunggakan SPP dari Pesantren;",
          path: "surat_keterangan_penunggakan_spp_dari_pesantren",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Hafalan  dari Pesantren Minimal 3 Juz;",
          path: "surat_keterangan_hafalan_minimal_3_juz",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Perjanjian untuk Menyelesaikan Hafalan Sesuai Target yaitu Selama 3 Tahun yang Ditanda Tangani Calon Hafiz dan Kedua Orang Tuanya.",
          path: "surat_perjanjian_untuk_menyelesaikan_hafalan_selama_3_tahun",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi ijazah terakhir",
          path: "foto_copy_ijazah_terakhir",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi KTP Orang Tua",
          path: "foto_copy_ktp_orang_tua",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan Aktif Sekolah",
          path: "surat_keterangan_aktif_sekolah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Raport terakhir",
          path: "foto_copy_raport_terakhir",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Buku Rekening atas Nama Siswa / atas Nama Keluarga yang Masih Dalam Satu KK",
          path: "foto_copy_buku_rekening_siswa_keluarga_dalam_satu_kk",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "SK Pembimbing",
          path: "sk_pembimbing",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Aktif Kuliah",
          path: "surat_aktif_kuliah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Transkrip Nilai Terakhir yang Telah Dilegalisir.",
          path: "foto_copy_transkrip_nilai_terakhir_yang_telah_dilegalisir",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi KTP / SIM/ Identitas Diri Lainnya",
          path: "foto_copy_ktp_sim_identitas_diri_lainnya",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Kartu Tanda Mahasiswa",
          path: "foto_copy_kartu_tanda_mahasiswa",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Passport",
          path: "foto_copy_pasport",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Visa",
          path: "foto_copy_visa",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Proposal / Rincian Anggaran Biaya (RAB);",
          path: "proposal_rincian_anggaran_biaya_rab",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Pernyataan Penggunaan Biaya",
          path: "surat_pernyataan_penggunaan_biaya",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Memorandum of Understanding (MoU) Apabila Bantuan Diberikan Lebih dari Rp. 10.000.000,-",
          path: "mou_jika_bantuan_lebih_10000000",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Nomor Rekening Bank Aceh Syari’ah atas Nama Lembaga / Pengurus.",
          path: "nomor_rekening_bank_aceh_syariah_atas_nama_lembaga_pengurus",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Aktif Sekolah",
          path: "surat_aktif_sekolah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Kartu Tanda Siswa / KTS",
          path: "kartu_tanda_siswa_kts",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi Buku Rekening Bank Aceh Syariah atas Nama Kepala Sekolah",
          path: "foto_copy_buku_rekening_atas_nama_kepala_sekolah",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surat Keterangan yang menjelaskan mustahik sebagai korban bencana kemanusian dari Reje Kampung.",
          path: "sk_korban_bencana_dari_reje",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Fotokopi KTP Ketua",
          path: "foto_copy_ktp_ketua",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Syarats", null, {});
  },
};
