name: CI/CD Deploy Aplikasi Baitulmal Aceh Tengah

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FRONT_IMAGE: muammar88/baitulmal_client:1.0.0
      BACK_IMAGE: muammar88/baitulmal_server:1.0.0

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Build and push client image
      run: |
        docker build -t $FRONT_IMAGE ./client
        docker push $FRONT_IMAGE

    - name: Build and push backend image
      run: |
        docker build -t $BACK_IMAGE ./server
        docker push $BACK_IMAGE

    - name: Deploy to Ubuntu server via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER_DATABASE_MACHINE }}
        key: ${{ secrets.SSH_PRIVATE_KEY_DATABASE_MACHINE }}
        script: |
          cd /home/dbmachine/baitulmal

          # Pull latest images
          docker pull $FRONT_IMAGE
          docker pull $BACK_IMAGE

          # Restart services
          docker-compose down
          docker-compose up -d --force-recreate

          # Run Sequelize migration and seed scripts
          docker-compose exec -T server npx sequelize-cli db:migrate:undo:all
          docker-compose exec -T server npx sequelize-cli db:migrate
          docker-compose exec -T server npx sequelize-cli db:seed:all
